# Keras Embedding Layer
***
Keras offers an embedding layer that can be used for neural networks on text data. It requires the that input data be integer encoded, so that each word is represented by a unique integer. The embedding layer is initialized with random weights and will learn an embedding for all of the words in the training dataset. You can use this layer to:
* Learn a word embedding that can be saved and used in another model
* As part of a deep learning model where the embedding is learned along with the model itself
* Load a pre-trained word embedding model, a type of transfer learning

The embedding layer is defined as the first hidden layer of a network, and one must specify the 3 arguments:
* **input_dim** - the size of vocabulary
* **output_dim** - size of the semantic vector space
* **input_length** - the length of input sequences (you must add padding if necessary)

For example, this would define an Embedding layer with a vocabulary of 200 words (integers from 0 to 199), a vector space of 32 dimensions in which words will be embedded, and input documents having 50 words each.

The output of the embedding layer is a 2D vector with one embedding for each word in the input sequence of words.

If you want to connect a dense layer to an embedding layer, you must flatten the 2D output matrix into a 1D vector using the flatten layer.

The example we will look at is that of text classification problem. We will learn a word embedding while fitting a neural network to solve this problem. 

## Define the Data and Labels
***

In [2]:
import numpy as np
docs = ['Well done!',
    'Good work',
    'Great effort',
    'nice work',
    'Excellent!',
    'Weak',
    'Poor effort!',
    'not good',
    'poor work',
    'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

Now we integer encode each document. We need each input to the embedding layer to be a sequence of integers. We will do a one-hot encoding here. 

In [5]:
from keras.preprocessing.text import one_hot
vocab_size = 50
encoded_documents = [one_hot( document, vocab_size ) for document in docs]
print(encoded_documents)

[[32, 36], [36, 21], [30, 21], [16, 21], [47], [44], [28, 21], [45, 36], [28, 21], [21, 19, 36, 14]]


## Encode Data as Sequence of Integers and Pad The Sequences
***
Because we want all of these sequences of integers to be of the same length for Keras, we need to also pad the vectors with zeros:

In [9]:
from keras.preprocessing.sequence import pad_sequences

max_length = max([len(sequence) for sequence in encoded_documents])
padded_docs = pad_sequences(encoded_documents, maxlen=max_length, padding="post")
print(padded_docs)

[[32 36  0  0]
 [36 21  0  0]
 [30 21  0  0]
 [16 21  0  0]
 [47  0  0  0]
 [44  0  0  0]
 [28 21  0  0]
 [45 36  0  0]
 [28 21  0  0]
 [21 19 36 14]]


## Create Neural Network with Embedding Layer
***
We have a vocabulary of 50 and an input length of 4. We choose a small embedding space of 8 dimensions. We train a simple binary classification model. The output of our embedding layer will be 4 vectors of 8 dimensions each (one vector for each word). We will flatten this into a 32-element one dimensional vector and pass to a dense layer

In [13]:
from keras.models import Sequential
from keras.layers import Embedding, Dense, Flatten
model = Sequential()
model.add(Embedding(vocab_size,8,input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_2 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


## Fit and Evaluate the Classification Model
***
Now we can fit and evaluate the classification model:

In [15]:
model.fit(padded_docs, labels, epochs=100, verbose=1)
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)
print("Accuracy: {}".format(accuracy*100))

Epoch 1/100
10/10 [==============================] - 0s 302us/step - loss: 0.6103 - acc: 0.8000
Epoch 2/100
10/10 [==============================] - 0s 311us/step - loss: 0.6085 - acc: 0.8000
Epoch 3/100
10/10 [==============================] - 0s 334us/step - loss: 0.6067 - acc: 0.8000
Epoch 4/100
10/10 [==============================] - 0s 312us/step - loss: 0.6048 - acc: 0.8000
Epoch 5/100
10/10 [==============================] - 0s 421us/step - loss: 0.6030 - acc: 0.8000
Epoch 6/100
10/10 [==============================] - 0s 321us/step - loss: 0.6011 - acc: 0.8000
Epoch 7/100
10/10 [==============================] - 0s 314us/step - loss: 0.5993 - acc: 0.8000
Epoch 8/100
10/10 [==============================] - 0s 499us/step - loss: 0.5974 - acc: 1.0000
Epoch 9/100
10/10 [==============================] - 0s 449us/step - loss: 0.5955 - acc: 1.0000
Epoch 10/100
10/10 [==============================] - 0s 241us/step - loss: 0.5936 - acc: 1.0000
Epoch 11/100
10/10 [===================

Epoch 86/100
10/10 [==============================] - 0s 266us/step - loss: 0.4378 - acc: 1.0000
Epoch 87/100
10/10 [==============================] - 0s 297us/step - loss: 0.4357 - acc: 1.0000
Epoch 88/100
10/10 [==============================] - 0s 257us/step - loss: 0.4336 - acc: 1.0000
Epoch 89/100
10/10 [==============================] - 0s 239us/step - loss: 0.4316 - acc: 1.0000
Epoch 90/100
10/10 [==============================] - 0s 306us/step - loss: 0.4295 - acc: 1.0000
Epoch 91/100
10/10 [==============================] - 0s 269us/step - loss: 0.4275 - acc: 1.0000
Epoch 92/100
10/10 [==============================] - 0s 244us/step - loss: 0.4254 - acc: 1.0000
Epoch 93/100
10/10 [==============================] - 0s 278us/step - loss: 0.4234 - acc: 1.0000
Epoch 94/100
10/10 [==============================] - 0s 398us/step - loss: 0.4213 - acc: 1.0000
Epoch 95/100
10/10 [==============================] - 0s 317us/step - loss: 0.4193 - acc: 1.0000
Epoch 96/100
10/10 [==========

# Using Pre-Trained GloVe Embedding
***

We need to be able to map words to integers as well as integers to words. We use the `Tokenizer` class from Keras to generate this mapping. 
## Use Tokenizer To Encode Sequences
***

In [16]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
vocab_size = len(tokenizer.word_index) + 1
encoded_docs = tokenizer.texts_to_sequences(docs)
print(encoded_docs)
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding="post")
print(padded_docs)

[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]
[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


## Load GloVe Embeddings into Memory
***
Now we load the entire GloVe word embedding file into memory as a dictionary of words to the embedding array:

In [17]:
embeddings_index = {}
with open("data/glove_wikipedia_embeddings/glove.6B.100d.txt") as f:
    for line in f:
        columns = line.split()
        word = columns[0]
        weights = np.array(columns[1:])
        embeddings_index[word] = weights
print("Loaded {} word vectors".format(len(embeddings_index)))    

Loaded 400000 word vectors


## Create a Matrix of Embedding Weights for all the Words in Training Set
***
Enumerate the unique words in `Tokenizer.word_index` and then locate the corresponding weight vector from the loaded GloVe embedding.

In [18]:
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

Now we can define and fit our model as before:

In [20]:
model = Sequential()
model.add(Embedding(vocab_size,100,weights=[embedding_matrix],input_length=max_length,\
                   trainable=False))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 4, 100)            1500      
_________________________________________________________________
flatten_3 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 401       
Total params: 1,901
Trainable params: 401
Non-trainable params: 1,500
_________________________________________________________________
None


In [21]:
model.fit(padded_docs, labels, epochs=50, verbose=1)
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)
print("Accuracy: {}".format(accuracy*100))

Epoch 1/50
10/10 [==============================] - 0s 24ms/step - loss: 0.7068 - acc: 0.6000
Epoch 2/50
10/10 [==============================] - 0s 199us/step - loss: 0.6925 - acc: 0.6000
Epoch 3/50
10/10 [==============================] - 0s 258us/step - loss: 0.6788 - acc: 0.6000
Epoch 4/50
10/10 [==============================] - 0s 253us/step - loss: 0.6658 - acc: 0.7000
Epoch 5/50
10/10 [==============================] - 0s 406us/step - loss: 0.6532 - acc: 0.7000
Epoch 6/50
10/10 [==============================] - 0s 325us/step - loss: 0.6412 - acc: 0.7000
Epoch 7/50
10/10 [==============================] - 0s 274us/step - loss: 0.6297 - acc: 0.7000
Epoch 8/50
10/10 [==============================] - 0s 259us/step - loss: 0.6186 - acc: 0.7000
Epoch 9/50
10/10 [==============================] - 0s 283us/step - loss: 0.6079 - acc: 0.7000
Epoch 10/50
10/10 [==============================] - 0s 373us/step - loss: 0.5975 - acc: 0.7000
Epoch 11/50
10/10 [==============================]